services:

  db:
    image: postgres
    container_name: spa-db
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - backend-net
    profiles:
      - dev
      - prod
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'

networks:
  backend-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.191.0.0/16